apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argo-cd.argoproj.io
spec:
  project: argo-cd-settings
  source:
    repoURL: https://github.com/Rogembaum/templates.git
    targetRevision: HEAD
    path: argo-cd/apps
    directory:
      recurse: true
      include: "*.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
