apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argo-cd-settings
  namespace: argo-cd
  finalizers:
    - argoproj.io/resources-finalizer
spec:
  description: "argo-cd settings project for infrastructure"
  sourceRepos:
    # Git repositories
    - 'https://github.com/Rogembaum/templates.git'
    # Helm repositories
    - 'https://helm.releases.hashicorp.com'
    - 'https://charts.bitnami.com/bitnami'
    - 'https://charts.external-secrets.io' 
  destinations:
      - namespace: "*"
        server: "*"
        name: "*"
  clusterResourceBlacklist:
      - group: '*'
        kind: '*'
  namespaceResourceWhitelist:
    - group: argoproj.io
      kind: Application
    - group: argoproj.io
      kind: ApplicationSet
