apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argo-cd-settings
  namespace: argocd
  finalizers:
    - argoproj.io/resources-finalizer
spec:
  description: "ArgoCD settings project for infrastructure"
  sourceRepos:
    - 'https://github.com/Rogembaum/templates.git'  
  destinations:
      - namespace: "*"
        server: "*"
        name: "*"
  clusterResourceBlacklist:
      - group: '*'
        kind: '*'
  namespaceResourceWhitelist:
    - group: argoproj.io
      kind: Application
    - group: argoproj.io
      kind: ApplicationSet
