apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argo-cd.argoproj.io
spec:
  project: infra-project
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: v0.14.3
    helm:
      values: |
        installCRDs: true
        
        webhook:
          port: 9443
        
        certController:
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 50m
              memory: 50Mi
        
        # RBAC настройки
        rbac:
          create: true
          serviceAccount:
            create: true
            name: external-secrets-sa
            annotations: {}
        
        # Ресурсы для оператора
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 50Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets-system
  
  syncPolicy:
    automated:
      prune: true # Automatically prune resources if they are not present in the git
      selfHeal: true # Automatically heal resources if they are not present in the git,ex with kubectl
    syncOptions:
      - CreateNamespace=true # Create namespace if it does not exist
      - PrunePropagationPolicy=foreground # Prune propagation policy:ex. first delete resources in the namespace, then delete the namespace
      - PruneLast=true # Prune last, ex. delete all resources in the namespace, then delete the namespace
      - RespectIgnoreDifferences=true # Respect ignore differences
