apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: argocd
  finalizers:
    - resources-finalizer.argo-cd.argoproj.io
spec:
  project: infra-project
  source:
    repoURL: oci://registry.gitlab.com/gitlab-org/charts/gitlab
    chart: gitlab
    targetRevision: 9.4.0
    helm:
      values: |
        global:
          # GitLab configuration
          hosts:
            domain: gitlab.example.com
            https: false
            gitlab:
              name: GitLab
            minio:
              name: MinIO
            registry:
              name: Registry
          
          # Ingress configuration
          ingress:
            enabled: false
            class: nginx
            annotations:
              nginx.ingress.kubernetes.io/rewrite-target: /
              cert-manager.io/cluster-issuer: letsencrypt-prod
            tls:
              enabled: true
              secretName: gitlab-tls
          
          # PostgreSQL configuration
          psql:
            host: postgresql
            port: 5432
            database: gitlabhq_production
            username: gitlab
            password:
              secret: gitlab-postgresql-password
              key: postgresql-password
          
          # Redis configuration
          redis:
            host: redis
            port: 6379
            password:
              secret: gitlab-redis-password
              key: redis-password
          
          # MinIO configuration
          minio:
            enabled: true
            host: minio
            port: 9000
            accessKey:
              secret: gitlab-minio-secret
              key: accesskey
            secretKey:
              secret: gitlab-minio-secret
              key: secretkey
            bucket: gitlab-storage
        
        # GitLab Rails application
        gitlab:
          gitaly:
            enabled: true
            persistence:
              enabled: true
              size: 50Gi
            resources:
              requests:
                memory: 1Gi
                cpu: 500m
              limits:
                memory: 2Gi
                cpu: 1000m
          
          gitlab-shell:
            enabled: true
            resources:
              requests:
                memory: 256Mi
                cpu: 100m
              limits:
                memory: 512Mi
                cpu: 200m
          
          sidekiq:
            enabled: true
            replicas: 2
            resources:
              requests:
                memory: 1Gi
                cpu: 500m
              limits:
                memory: 2Gi
                cpu: 1000m
          
          webservice:
            enabled: true
            replicas: 2
            resources:
              requests:
                memory: 1Gi
                cpu: 500m
              limits:
                memory: 2Gi
                cpu: 1000m
            workhorse:
              resources:
                requests:
                  memory: 256Mi
                  cpu: 100m
                limits:
                  memory: 512Mi
                  cpu: 200m
        
        # PostgreSQL
        postgresql:
          enabled: true
          image:
            tag: "15.4.0"
          auth:
            postgresPassword: "gitlab-postgres-password"
            username: "gitlab"
            password: "gitlab-postgres-password"
            database: "gitlabhq_production"
          primary:
            persistence:
              enabled: true
              size: 20Gi
            resources:
              requests:
                memory: 1Gi
                cpu: 500m
              limits:
                memory: 2Gi
                cpu: 1000m
        
        # Redis
        redis:
          enabled: true
          image:
            tag: "7.0.11"
          auth:
            enabled: true
            password: "gitlab-redis-password"
          master:
            persistence:
              enabled: true
              size: 10Gi
            resources:
              requests:
                memory: 256Mi
                cpu: 100m
              limits:
                memory: 512Mi
                cpu: 200m
        
        # MinIO
        minio:
          enabled: true
          image:
            tag: "RELEASE.2023-08-29T23-07-35Z"
          auth:
            rootUser: "minio"
            rootPassword: "gitlab-minio-password"
          defaultBuckets: "gitlab-storage"
          persistence:
            enabled: true
            size: 50Gi
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 200m
        
        # Registry
        registry:
          enabled: true
          image:
            tag: "3.90.0-gitlab"
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 200m
        
        # Prometheus monitoring
        prometheus:
          enabled: false
          install: true
          server:
            resources:
              requests:
                memory: 512Mi
                cpu: 200m
              limits:
                memory: 1Gi
                cpu: 500m
            persistentVolume:
              enabled: true
              size: 10Gi
        
        # Grafana monitoring
        grafana:
          enabled: false
          install: true
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 200m
          persistence:
            enabled: true
            size: 5Gi

  destination:
    server: https://kubernetes.default.svc
    namespace: gitlab
  
  syncPolicy:
    automated:
      prune: true # Automatically prune resources if they are not present in the git
      selfHeal: true # Automatically heal resources if they are not present in the git,ex with kubectl
    syncOptions:
      - CreateNamespace=true # Create namespace if it does not exist
      - PrunePropagationPolicy=foreground # Prune propagation policy:ex. first delete resources in the namespace, then delete the namespace
      - PruneLast=true # Prune last, ex. delete all resources in the namespace, then delete the namespace
      - RespectIgnoreDifferences=true # Respect ignore differences
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: gitlab-postgresql-password
      jsonPointers:
        - /data
    - group: ""
      kind: Secret
      name: gitlab-redis-password
      jsonPointers:
        - /data
    - group: ""
      kind: Secret
      name: gitlab-minio-secret
      jsonPointers:
        - /data
