---
- name: Install apache and upload index.html
  hosts: all
  become: true

  vars:
   src_folder : ./mysite
   dest_folder: /var/www/html

  tasks:


#=======Start Block Debian=======
  - block:
      - name: Install web-server Debian
        package:
          name: apache2
          state: latest

      - name: Start web-server & enable on boot Debian
        service: name=apache2 state=started enabled=yes

    when: ansible_os_family == "Debian"
#=======End Block Debian=======


#=======Start Block RedHat=======
  - block:

    - name: Install web-server RedHat
      package:
        name: httpd
        state: latest

    - name: Start web-server & enable on boot RedHat
      service: name=httpd state=started enabled=yes

    - name: Enable 80 port
      firewalld:
        service: http
        permanent: yes
        state: enabled

    when: ansible_os_family == "RedHat"
#=======End Block RedHat=======

  - name: Generate index.html file
    template: src={{ src_folder}}/index.j2 dest={{ dest_folder }}/index.html mode=0555
    notify:
      - Restart web-server RedHat
      - Restart web-server Debian

  - name: Copy index.html to servers
    copy: 
      src: "{{ item }}"
      dest: "{{ dest_folder }}"
      mode: 0555
    with_fileglob:
      - "{{ src_folder }}/*"
    notify:
      - Restart web-server RedHat
      - Restart web-server Debian


  handlers:
   - name: Restart web-server RedHat
     service: name=httpd state=restarted
     when: ansible_os_family == "RedHat"

   - name: Restart web-server Debian
     service: name=apache2 state=restarted
     when: ansible_os_family == "Debian"
...