# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'no'

Vagrant.configure(2) do |config|
  config.vm.synced_folder ".", "/vagrant_data", disabled: true

  #config.vm.provision "shell", path: "bootstrap.sh"
  #### 'это применяется для всех машин - скорей всего тут будут ключи'

  # graylog
  config.vm.define "graylog" do |graylog|
    graylog.vm.box = "generic/centos8"
    graylog.vm.hostname = "graylog.local.net"
    graylog.vm.network "public_network", 
      bridge: "vLAN"
    graylog.vm.provider "hyperv" do |v|
      v.vmname = "graylog"
      v.memory = 2048
      v.cpus = 2
      v.enable_virtualization_extensions = false
      v.linked_clone = true
      v.vm_integration_services = {
        guest_service_interface: true,
        time_synchronization: true
      } 
    end
    graylog.vm.provision "shell", path: "bootstrap_graylog.sh"
  end


end