#!/bin/bash

# pid
$$

# list of namespace where process is working
ls -la /proc/$$/ns


# list namespace
lsns

# enter to namespace
nsenter

# list process with cmd,cpu
ps -eo cmd,%cpu --sort=%cpu

# comands
    #find cmd
    ctrl+r
    
    # rm left from cursor
    ctrl+w
    
    #paste last arg
    alt+.

    #input cmds thr editor
    ctrl+x+e

    #repeat cmd
    !!

    #lists in cmd
    {}

    #repeat cmd with interval
    watch

    #return proc from SIGSTOP (ctrl+Z) to front
    fg

    #return proc from SIGSTOP (ctrl+Z) to back
    bg

    #get all stoped procs
    jobs

    # rm empty or commented strings
    grep -v "^$\|^#"
    grep -v '^ *#'

    # ignore register
    grep -i

    # . any symbol
    cat /etc/ssh/ssh_config  | grep .  | grep -v "^#"

    # out 2nd column
    ps aux | grep sleep | grep -v grep | awk '{print $2}'

    # set delimeter to : and out all usernames
    cat /etc/passwd | awk -F: '{print $1,$3}' | column -t

    # cng
    sed -i "s/PermitRootLogin yes/PermitRootLogin no/" /etc/ssh/sshd_config

    # recursive searching
    grep -r "ssh" /etc

    #
    echo "123" | tee test{1..100}


sftp -r -P PORT -i .\id_ed25519 root@IP:/remote/path local/patg



grep -r "@domain.com" . | grep To | awk '{print $2}' | sort | uniq

grep -Rnw '/path/to/somewhere/' -e 'pattern'

grep -Ril "text-to-find-here" /

grep -v "#" /etc/apt/sources.list.d/ubuntu.sources


###################
### replace a string with sed in current and recursive subdirectories
###################

find . -type f -exec sed -i 's/foo/bar/g' {} +

# To ignore hidden files (such as .git) you can pass the negation modifier -not -path '*/\.*', like this:
find . -type f -not -path '*/\.*' -exec sed -i 's/foo/bar/g' {} +

find . -type f -name "*.md" -exec sed -i 's/foo/bar/g' {} +



##############################
## Install security updates ##
##############################
apt-get -s dist-upgrade |grep "^Inst" |grep -i securi 

or

sudo unattended-upgrade --dry-run -d

or

/usr/lib/update-notifier/apt-check -p

Show all upgradeable packages

apt-get -s dist-upgrade | grep "^Inst"

Install security updates only

apt-get -s dist-upgrade | grep "^Inst" | 
    grep -i securi | awk -F " " {'print $2'} | 
    xargs apt-get install
#-----------------------------------------

# how many packets installed in os
dpkg -l | grep ^ii | wc -l
dpkg --list

# which packet include binary file
dpkg -S /usr/bin/ls
or
dpkg -S /etc/nginx.conf

# how many files in packet
dpkg -L coreutils

# search in local packege cache
apt-cache search apache




# rm protect you from delete /, but this is not work for /*
rm -rf /

# run login shell as the target user
# for example for root /BIN/BASH
# cat /etc/passwd | grep root
# root:x:0:0:root:/root:/bin/bash
sudo -i
LIKE 
sudo /bin/bash

# use target user's shell
# This account is currently not available.
# cat /etc/passwd | grep daemon
# daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
sudo -i -u daemon

# use current user's shell
# cat /etc/passwd | grep ray
# ray:x:1000:1000:,,,:/home/ray:/bin/bash
sudo -s -u daemon
whoami
daemon

# to get distr version
lsb_release  -a